on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    env:
      POETRY_VIRTUALENVS_CREATE: false 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: pip3 install poetry
    - name: Install dependencies
      run: poetry install --no-root --all-extras
    - name: Test
      run: pytest

  lint:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install poetry
      run: pip3 install poetry
    - name: Install dependencies
      run: poetry install --no-root --all-extras
    - name: Lint
      run: make lint

  check-format:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install poetry
      run: pip3 install poetry
    - name: Install dependencies
      run: poetry install --no-root --all-extras
    - name: Check format
      run: make check-format
